sudo: required

language: generic

services:
  - docker

before_install:
 - echo "start Creating an image with dockerfile"
 - docker build -t polya/react-app -f Dockerfile.dev ./

script:
  - docker run -e CI=true polya/react-app npm run test -- --coverage

deploy:
  provider : elasticbeanstalk
  region: ap-northeast-2
  app: "docker-react-app"
  env: "DockerReactApp-env"
  bucket-name: "elasticbeanstalk-ap-northeast-2-709296188990"
  bucket-path: :"docker-react-app"
  on:
    branch: master


after_success:
  - echo "Test Success." 

